INSERT INTO crate_rewards (crate_type, reward_type, reward_value, reward_metadata, weight, is_jackpot) VALUES
('bronze', 'rc_payout', 50, NULL, 30, false),
('bronze', 'rc_payout', 100, NULL, 25, false),
('bronze', 'rc_payout', 150, NULL, 15, false),
('bronze', 'rc_payout', 200, NULL, 10, false),
('bronze', 'discount_token', NULL, '{"discountAmount": "1.00"}', 8, false),
('bronze', 'nothing', NULL, NULL, 10, false),
('bronze', 'rc_payout', 300, NULL, 2, true),
('silver', 'rc_payout', 200, NULL, 25, false),
('silver', 'rc_payout', 400, NULL, 20, false),
('silver', 'rc_payout', 600, NULL, 15, false),
('silver', 'discount_token', NULL, '{"discountAmount": "5.00"}', 12, false),
('silver', 'jackpot_raffle_ticket', 1, NULL, 8, false),
('silver', 'nothing', NULL, NULL, 15, false),
('silver', 'rc_payout', 900, NULL, 5, true),
('gold', 'rc_payout', 500, NULL, 20, false),
('gold', 'rc_payout', 1000, NULL, 18, false),
('gold', 'rc_payout', 1500, NULL, 12, false),
('gold', 'discount_token', NULL, '{"discountAmount": "10.00"}', 10, false),
('gold', 'cosmetic_role', NULL, '{"roleId": "0", "temporary": true}', 5, false),
('gold', 'jackpot_raffle_ticket', 3, NULL, 5, true),
('gold', 'nothing', NULL, NULL, 25, false),
('gold', 'rc_payout', 3000, NULL, 5, true);
